[package]
name = "noise-suppression-common"
version.workspace = true
edition.workspace = true

[dependencies]
nnnoiseless = { version = "0.5", default-features = false, features = ["dasp"] }
dasp_sample = "0.11"
