[package]
name = "noise-suppression-common"
version = "0.1.0"
authors = ["John Peel <john@dgby.org>"]
edition = "2018"

[dependencies]
nnnoiseless = { version = "0.3", default-features = false, features = [] }
dasp_sample = "0.11"
