[package]
name = "noise-suppression-mono-vst2"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
noise-suppression-common = { path = "../noise-suppression-common" }
vst = "0.4"
