[package]
name = "noise-suppression-lv2"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
noise-suppression-common = { path = "../noise-suppression-common" }
lv2 = { version = "0.6", default-features = false, features = [ "minimal_plugin" ] }
