[package]
name = "noise-suppression-ladspa"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
noise-suppression-common = { path = "../noise-suppression-common" }
ladspa = "0.3"
