[package]
name = "noise-suppression-stereo-vst2"
version = "0.1.0"
authors = ["John Peel <john@dgby.org>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
noise-suppression-common = { path = "../noise-suppression-common" }
vst = "0.2"
