name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - stable
          # - beta
          # - nightly
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        include:
          - os: ubuntu-latest
            cargo_args: --all
            ext: so
            libprefix: lib
            strip_args: --strip-all
          - os: windows-latest
            cargo_args: --all --exclude noise-suppression-lv2 --exclude noise-suppression-ladspa
            ext: dll
            libprefix:
            strip_args: --strip-all
          - os: macos-latest
            cargo_args: --all --exclude noise-suppression-lv2 --exclude noise-suppression-ladspa
            ext: dylib
            libprefix: lib
            strip_args:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            !target/release/${{ matrix.libprefix }}noise_suppression_*.${{ matrix.ext }}
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: ${{ matrix.cargo_args }} -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: ${{ matrix.cargo_args }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: ${{ matrix.cargo_args }} --release
      - name: Strip Binaries
        run: strip ${{ matrix.strip_args }} target/release/${{ matrix.libprefix }}noise_suppression_*.${{ matrix.ext }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-artifacts
          path: target/release/${{ matrix.libprefix }}noise_suppression_*.${{ matrix.ext }}
