name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust:
          - stable
          # - beta
          # - nightly
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        project:
          - lv2
          - ladspa
          - mono-vst2
          - stereo-vst2
        exclude:
          - os: macos-latest
            project: lv2
        include:
          - os: ubuntu-latest
            ext: so
            libprefix: lib
            strip: true
            strip_args: --strip-all
          - os: windows-latest
            ext: dll
            libprefix:
            strip: true
            strip_args: --strip-all
          - os: macos-latest
            ext: dylib
            libprefix: lib
            strip: false
            strip_args:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
            !target/release/${{ matrix.libprefix }}noise_suppression_*.${{ matrix.ext }}
          key: ${{ runner.os }}-${{ matrix.rust }}-cargo
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy
      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --package noise-suppression-${{ matrix.project }} -- -D warnings
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --package noise-suppression-${{ matrix.project }}
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --package noise-suppression-${{ matrix.project }} --release
      - name: Strip Binaries
        run: strip ${{ matrix.strip_args }} target/release/${{ matrix.libprefix }}noise_suppression_*.${{ matrix.ext }}
        if: ${{ matrix.strip }}
      - uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-${{ matrix.project }}
          path: target/release/${{ matrix.libprefix }}noise_suppression_*.${{ matrix.ext }}
